sudo: required
services:
  - docker
before_install:
  - docker build -t sivanesanm/newrepo:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push sivanesanm/newrepo:v1.0
notifications:
  email:
    recipients:
      - bshivha@gmail.com
    on_success: always
    on_failure: always
